### PR TITLE
Adapt `ps_newproducts` for multiples versions of PrestaShop

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Adapt `ps_newproducts` for multiples versions of PrestaShop
| Type?         | refacto
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Relative to PrestaShop/Prestashop#28988
| How to test?  | Try this module in version `< 1.7.4.0` and in recent version (`8.0.0`)

### CODE REVIEW

**Review by Hlavtox — APPROVED** [review]
The same as https://github.com/PrestaShop/ps_specials/pull/10/files.

**Review by nicosomb — APPROVED** [review]

**Comment by nicosomb** [comment]
Thank you @Progi1984 !

**Comment by Progi1984** [comment]
@nicosomb Don't you forget the @PrestaShop/qa-functional ?

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @Progi1984 

I have checked that your PR works fine with the `ps_newproducts `module even after being merged.

- Check on PS1733 with php 7.1 : OK
- Check on PS8.0.1 with php 8.1 : OK
- Check with multistore: OK

So, it's QA :heavy_check_mark:

**Comment by nicosomb** [comment]
Thank you so much @HanaRebaiQA and sorry for my mistake.

**Comment by HanaRebaiQA** [comment]
You are welcome! no problem :)

**Pull request merged**
